---
version: "3.8"
networks:
  proxy:
    external: true
services:
  aapindia:
    container_name: aapindia
    networks: [proxy]
    build:
      context: .
      target: runtime
    env_file: .env
    environment:
      NODE_ENV: production
